import {Contacto} from "../types/contactos" 

export const mockContactos: Contacto[] = [
    // ==================== EMPRESAS ====================
    {
        id_empresa: 1,
        ruc: "20123456789",
        razon_social: "ACME SOLUCIONES EMPRESARIALES S.A.C.",
        condicion: "ACTIVO",
        nombre_comercial: "ACME",
        correo_corporativo: "contacto@acme.com.pe",
        celular_corporativo: "+51 987 654 321",
        sitio_web: "www.acme.com.pe",
        actividad_economica: "Consultoría en tecnología",
        direccion: "Av. Javier Prado Este 476",
        fecha_creacion: "2023-01-15",
        fecha_actualizacion: "2024-11-20"
    },
    {
        id_empresa: 2,
        ruc: "20987654321",
        razon_social: "CONSTRUCTORA BETA S.R.L.",
        condicion: "ACTIVO",
        nombre_comercial: "BETA Construcciones",
        correo_corporativo: "info@beta.pe",
        celular_corporativo: "+51 956 789 123",
        actividad_economica: "Construcción de edificios",
        direccion: "Calle Las Begonias 234",
        fecha_creacion: "2022-06-10",
        fecha_actualizacion: "2024-12-01"
    },
    {
        id_empresa: 3,
        ruc: "20456789123",
        razon_social: "TECNOLOGÍA GAMMA E.I.R.L.",
        condicion: "ACTIVO",
        correo_corporativo: "ventas@tecgamma.com",
        celular_corporativo: "+51 912 345 678",
        sitio_web: "www.tecgamma.com",
        actividad_economica: "Venta de equipos de cómputo",
        fecha_creacion: "2021-03-22",
        fecha_actualizacion: "2024-10-15"
    },
    {
        id_empresa: 4,
        ruc: "20789456123",
        razon_social: "ALIMENTOS DEL PACÍFICO S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "Alipac",
        correo_corporativo: "contacto@alipac.pe",
        celular_corporativo: "+51 945 678 912",
        sitio_web: "www.alipac.pe",
        actividad_economica: "Procesamiento de alimentos",
        direccion: "Av. Argentina 1234",
        fecha_creacion: "2020-08-05",
        fecha_actualizacion: "2024-11-28"
    },
    {
        id_empresa: 5,
        ruc: "20321654987",
        razon_social: "TEXTILES ANDINOS S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "info@textilesandinos.com",
        actividad_economica: "Fabricación de textiles",
        fecha_creacion: "2019-05-12",
        fecha_actualizacion: "2024-09-20"
    },
    {
        id_empresa: 6,
        ruc: "20654987321",
        razon_social: "MINERA DORADA DEL SUR S.A.C.",
        condicion: "ACTIVO",
        nombre_comercial: "Minera Dorada",
        correo_corporativo: "contacto@mineradorada.pe",
        celular_corporativo: "+51 923 456 789",
        sitio_web: "www.mineradorada.pe",
        actividad_economica: "Extracción de minerales",
        direccion: "Jr. Carabaya 567",
        fecha_creacion: "2018-11-30",
        fecha_actualizacion: "2024-12-05"
    },
    {
        id_empresa: 7,
        ruc: "20147258369",
        razon_social: "SERVICIOS LOGÍSTICOS EXPRESS S.R.L.",
        condicion: "ACTIVO",
        nombre_comercial: "LogiExpress",
        correo_corporativo: "operaciones@logiexpress.pe",
        celular_corporativo: "+51 934 567 890",
        actividad_economica: "Transporte y logística",
        fecha_creacion: "2021-07-18",
        fecha_actualizacion: "2024-11-15"
    },
    {
        id_empresa: 8,
        ruc: "20258369147",
        razon_social: "FARMACÉUTICA SALUD TOTAL S.A.",
        condicion: "ACTIVO",
        correo_corporativo: "info@saludtotal.pe",
        celular_corporativo: "+51 967 890 123",
        sitio_web: "www.saludtotal.pe",
        actividad_economica: "Venta de productos farmacéuticos",
        direccion: "Av. La Marina 890",
        fecha_creacion: "2020-02-14",
        fecha_actualizacion: "2024-10-22"
    },
    {
        id_empresa: 9,
        ruc: "20369147258",
        razon_social: "EDUCACIÓN GLOBAL PERÚ S.A.C.",
        condicion: "ACTIVO",
        nombre_comercial: "EduGlobal",
        correo_corporativo: "admision@eduglobal.edu.pe",
        celular_corporativo: "+51 978 901 234",
        sitio_web: "www.eduglobal.edu.pe",
        actividad_economica: "Servicios educativos",
        fecha_creacion: "2022-01-10",
        fecha_actualizacion: "2024-11-30"
    },
    {
        id_empresa: 10,
        ruc: "20741852963",
        razon_social: "AUTOMOTRIZ VELOZ S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "ventas@veloz.pe",
        celular_corporativo: "+51 989 012 345",
        actividad_economica: "Venta de vehículos",
        direccion: "Av. Faucett 1456",
        fecha_creacion: "2019-09-25",
        fecha_actualizacion: "2024-12-02"
    },
    {
        id_empresa: 11,
        ruc: "20852963741",
        razon_social: "INMOBILIARIA PACIFIC HOMES S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "Pacific Homes",
        correo_corporativo: "info@pacifichomes.pe",
        celular_corporativo: "+51 990 123 456",
        sitio_web: "www.pacifichomes.pe",
        actividad_economica: "Desarrollo inmobiliario",
        fecha_creacion: "2021-04-08",
        fecha_actualizacion: "2024-11-18"
    },
    {
        id_empresa: 12,
        ruc: "20963741852",
        razon_social: "AGROINDUSTRIAS DEL VALLE S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "contacto@agrovalle.pe",
        actividad_economica: "Producción agrícola",
        direccion: "Km 15 Panamericana Sur",
        fecha_creacion: "2020-06-20",
        fecha_actualizacion: "2024-10-30"
    },
    {
        id_empresa: 13,
        ruc: "20135792468",
        razon_social: "TELECOMUNICACIONES ANDINAS S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "TeleAndina",
        correo_corporativo: "soporte@teleandina.pe",
        celular_corporativo: "+51 901 234 567",
        sitio_web: "www.teleandina.pe",
        actividad_economica: "Servicios de telecomunicaciones",
        fecha_creacion: "2018-12-15",
        fecha_actualizacion: "2024-11-25"
    },
    {
        id_empresa: 14,
        ruc: "20246813579",
        razon_social: "ENERGÍA RENOVABLE PERÚ S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "info@energiarenovable.pe",
        celular_corporativo: "+51 912 345 670",
        actividad_economica: "Generación de energía solar",
        fecha_creacion: "2021-08-30",
        fecha_actualizacion: "2024-12-03"
    },
    {
        id_empresa: 15,
        ruc: "20357924681",
        razon_social: "HOTELERÍA COSTA AZUL S.R.L.",
        condicion: "ACTIVO",
        nombre_comercial: "Hotel Costa Azul",
        correo_corporativo: "reservas@costaazul.pe",
        celular_corporativo: "+51 923 456 781",
        sitio_web: "www.hotelcostaazul.pe",
        actividad_economica: "Servicios de alojamiento",
        direccion: "Malecón Cisneros 234",
        fecha_creacion: "2019-03-17",
        fecha_actualizacion: "2024-11-12"
    },
    {
        id_empresa: 16,
        ruc: "20468135792",
        razon_social: "PUBLICIDAD CREATIVA S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "contacto@pubcreativa.pe",
        celular_corporativo: "+51 934 567 892",
        actividad_economica: "Servicios de publicidad",
        fecha_creacion: "2022-05-22",
        fecha_actualizacion: "2024-10-18"
    },
    {
        id_empresa: 17,
        ruc: "20579246813",
        razon_social: "METALMECÁNICA INDUSTRIAL S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "MetalInd",
        correo_corporativo: "ventas@metalind.pe",
        celular_corporativo: "+51 945 678 903",
        actividad_economica: "Fabricación de estructuras metálicas",
        direccion: "Av. Industrial 789",
        fecha_creacion: "2020-10-05",
        fecha_actualizacion: "2024-11-22"
    },
    {
        id_empresa: 18,
        ruc: "20681357924",
        razon_social: "QUÍMICA Y PINTURAS DEL PERÚ S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "info@quimperu.pe",
        actividad_economica: "Fabricación de pinturas",
        fecha_creacion: "2019-07-14",
        fecha_actualizacion: "2024-09-28"
    },
    {
        id_empresa: 19,
        ruc: "20792468135",
        razon_social: "SEGURIDAD INTEGRAL S.R.L.",
        condicion: "ACTIVO",
        nombre_comercial: "SecurIntegral",
        correo_corporativo: "operaciones@securintegral.pe",
        celular_corporativo: "+51 956 789 014",
        sitio_web: "www.securintegral.pe",
        actividad_economica: "Servicios de seguridad privada",
        fecha_creacion: "2021-02-28",
        fecha_actualizacion: "2024-12-01"
    },
    {
        id_empresa: 20,
        ruc: "20803579246",
        razon_social: "RESTAURANTES SABOR PERUANO S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "contacto@saborperuano.pe",
        celular_corporativo: "+51 967 890 125",
        actividad_economica: "Servicios de restaurante",
        direccion: "Av. Larco 567",
        fecha_creacion: "2020-04-12",
        fecha_actualizacion: "2024-11-08"
    },
    {
        id_empresa: 21,
        ruc: "20914680357",
        razon_social: "EXPORTACIONES MARINAS S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "ExpoMar",
        correo_corporativo: "exportaciones@expomar.pe",
        celular_corporativo: "+51 978 901 236",
        sitio_web: "www.expomar.pe",
        actividad_economica: "Exportación de productos marinos",
        fecha_creacion: "2018-09-08",
        fecha_actualizacion: "2024-10-25"
    },
    {
        id_empresa: 22,
        ruc: "20025791468",
        razon_social: "LABORATORIOS MÉDICOS VIDA S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "info@labvida.pe",
        celular_corporativo: "+51 989 012 347",
        actividad_economica: "Análisis clínicos",
        direccion: "Jr. Tacna 890",
        fecha_creacion: "2021-11-19",
        fecha_actualizacion: "2024-11-27"
    },
    {
        id_empresa: 23,
        ruc: "20136802579",
        razon_social: "PLÁSTICOS INDUSTRIALES DEL SUR S.R.L.",
        condicion: "ACTIVO",
        correo_corporativo: "ventas@plasur.pe",
        actividad_economica: "Fabricación de productos plásticos",
        fecha_creacion: "2020-01-25",
        fecha_actualizacion: "2024-09-15"
    },
    {
        id_empresa: 24,
        ruc: "20247913680",
        razon_social: "EVENTOS Y PRODUCCIONES S.A.C.",
        condicion: "ACTIVO",
        nombre_comercial: "EventosPro",
        correo_corporativo: "contacto@eventospro.pe",
        celular_corporativo: "+51 990 123 458",
        sitio_web: "www.eventospro.pe",
        actividad_economica: "Organización de eventos",
        fecha_creacion: "2022-03-14",
        fecha_actualizacion: "2024-11-20"
    },
    {
        id_empresa: 25,
        ruc: "20358024791",
        razon_social: "MUEBLERÍA EL ROBLE S.A.",
        condicion: "ACTIVO",
        correo_corporativo: "ventas@elroble.pe",
        celular_corporativo: "+51 901 234 569",
        actividad_economica: "Fabricación de muebles",
        direccion: "Av. Universitaria 1234",
        fecha_creacion: "2019-06-30",
        fecha_actualizacion: "2024-10-12"
    },
    {
        id_empresa: 26,
        ruc: "20469135802",
        razon_social: "CONSULTORÍA EMPRESARIAL ESTRATÉGICA S.A.C.",
        condicion: "ACTIVO",
        nombre_comercial: "ConsuEstra",
        correo_corporativo: "info@consuestr.pe",
        celular_corporativo: "+51 912 345 680",
        actividad_economica: "Consultoría empresarial",
        fecha_creacion: "2021-09-05",
        fecha_actualizacion: "2024-12-04"
    },
    {
        id_empresa: 27,
        ruc: "20570246913",
        razon_social: "IMPRENTAS MODERNAS S.R.L.",
        condicion: "ACTIVO",
        correo_corporativo: "pedidos@impremod.pe",
        actividad_economica: "Servicios de impresión",
        fecha_creacion: "2020-07-22",
        fecha_actualizacion: "2024-11-10"
    },
    {
        id_empresa: 28,
        ruc: "20681357024",
        razon_social: "DISTRIBUIDORA NACIONAL DE BEBIDAS S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "DistriNac",
        correo_corporativo: "ventas@distrinac.pe",
        celular_corporativo: "+51 923 456 791",
        sitio_web: "www.distrinac.pe",
        actividad_economica: "Distribución de bebidas",
        direccion: "Av. Colonial 456",
        fecha_creacion: "2018-05-18",
        fecha_actualizacion: "2024-09-30"
    },
    {
        id_empresa: 29,
        ruc: "20792468135",
        razon_social: "ASESORÍA LEGAL CORPORATIVA S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "contacto@aseslegal.pe",
        celular_corporativo: "+51 934 567 802",
        actividad_economica: "Servicios legales",
        fecha_creacion: "2022-02-08",
        fecha_actualizacion: "2024-11-23"
    },
    {
        id_empresa: 30,
        ruc: "20803579246",
        razon_social: "CLIMATIZACIÓN Y REFRIGERACIÓN S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "ClimaFrío",
        correo_corporativo: "servicio@climafrio.pe",
        celular_corporativo: "+51 945 678 913",
        actividad_economica: "Instalación de sistemas de climatización",
        fecha_creacion: "2019-10-28",
        fecha_actualizacion: "2024-10-05"
    },
    {
        id_empresa: 31,
        ruc: "20914680357",
        razon_social: "JOYERÍA INCA GOLD S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "ventas@incagold.pe",
        sitio_web: "www.incagold.pe",
        actividad_economica: "Joyería y orfebrería",
        direccion: "Jr. de la Unión 234",
        fecha_creacion: "2021-12-15",
        fecha_actualizacion: "2024-11-28"
    },
    {
        id_empresa: 32,
        ruc: "20025791468",
        razon_social: "LAVANDERÍA INDUSTRIAL CLEAN PRO S.R.L.",
        condicion: "ACTIVO",
        nombre_comercial: "CleanPro",
        correo_corporativo: "operaciones@cleanpro.pe",
        celular_corporativo: "+51 956 789 024",
        actividad_economica: "Servicios de lavandería industrial",
        fecha_creacion: "2020-08-20",
        fecha_actualizacion: "2024-09-18"
    },
    {
        id_empresa: 33,
        ruc: "20136802579",
        razon_social: "CAFETERÍA AROMÁTICA S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "info@aromatica.pe",
        celular_corporativo: "+51 967 890 135",
        actividad_economica: "Venta de café y derivados",
        fecha_creacion: "2022-04-10",
        fecha_actualizacion: "2024-11-15"
    },
    {
        id_empresa: 34,
        ruc: "20247913680",
        razon_social: "CARPINTERÍA FINA MADERAS DEL NORTE S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "Maderas Norte",
        correo_corporativo: "contacto@maderasnorte.pe",
        celular_corporativo: "+51 978 901 246",
        sitio_web: "www.maderasnorte.pe",
        actividad_economica: "Carpintería y ebanistería",
        direccion: "Calle Los Pinos 678",
        fecha_creacion: "2019-02-28",
        fecha_actualizacion: "2024-10-22"
    },
    {
        id_empresa: 35,
        ruc: "20358024791",
        razon_social: "VETERINARIA MASCOTAS FELICES S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "citas@mascotasfelices.pe",
        actividad_economica: "Servicios veterinarios",
        fecha_creacion: "2021-06-05",
        fecha_actualizacion: "2024-12-02"
    },
    {
        id_empresa: 36,
        ruc: "20469135802",
        razon_social: "GIMNASIO FITNESS CENTER S.R.L.",
        condicion: "ACTIVO",
        nombre_comercial: "FitCenter",
        correo_corporativo: "info@fitcenter.pe",
        celular_corporativo: "+51 989 012 357",
        sitio_web: "www.fitcenter.pe",
        actividad_economica: "Servicios de gimnasio",
        fecha_creacion: "2020-03-18",
        fecha_actualizacion: "2024-11-05"
    },
    {
        id_empresa: 37,
        ruc: "20570246913",
        razon_social: "ARQUITECTURA Y DISEÑO MODERNOS S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "proyectos@arquimoderno.pe",
        celular_corporativo: "+51 990 123 468",
        actividad_economica: "Servicios de arquitectura",
        direccion: "Av. Arequipa 890",
        fecha_creacion: "2022-07-25",
        fecha_actualizacion: "2024-10-28"
    },
    {
        id_empresa: 38,
        ruc: "20681357024",
        razon_social: "FLORISTERÍA JARDÍN DE ROSAS S.A.",
        condicion: "ACTIVO",
        nombre_comercial: "Jardín de Rosas",
        correo_corporativo: "ventas@jardinrosas.pe",
        actividad_economica: "Venta de flores y plantas",
        fecha_creacion: "2019-11-12",
        fecha_actualizacion: "2024-09-25"
    },
    {
        id_empresa: 39,
        ruc: "20792468135",
        razon_social: "PELUQUERÍA Y SALÓN DE BELLEZA ELEGANCE S.A.C.",
        condicion: "ACTIVO",
        correo_corporativo: "citas@elegance.pe",
        celular_corporativo: "+51 901 234 579",
        sitio_web: "www.elegance.pe",
        actividad_economica: "Servicios de peluquería y belleza",
        fecha_creacion: "2021-01-30",
        fecha_actualizacion: "2024-11-18"
    },
    {
        id_empresa: 40,
        ruc: "20803579246",
        razon_social: "LIBRERÍA Y PAPELERÍA CULTURAL S.R.L.",
        condicion: "ACTIVO",
        nombre_comercial: "Cultural",
        correo_corporativo: "ventas@cultural.pe",
        celular_corporativo: "+51 912 345 690",
        actividad_economica: "Venta de libros y útiles",
        direccion: "Jr. Azángaro 345",
        fecha_creacion: "2020-05-08",
        fecha_actualizacion: "2024-12-03"
    },

    // ==================== PERSONAS ====================
    {
        id_persona: 1,
        id_empresa: 1,
        nombres_completos: "ALEXANDER ROY PACHECO LIZARRAGA",
        cargo: "GERENTE GENERAL",
        correo_personal: "alex.pacheco@gmail.com",
        celular_personal: "+51 912 345 678",
        fecha_creacion: "2023-01-15",
        fecha_actualizacion: "2024-10-05"
    },
    {
        id_persona: 2,
        id_empresa: 1,
        nombres_completos: "MARÍA FERNANDA TORRES GARCÍA",
        cargo: "JEFA DE PROYECTOS",
        correo_personal: "mf.torres@hotmail.com",
        celular_personal: "+51 923 456 789",
        fecha_creacion: "2023-03-20",
        fecha_actualizacion: "2024-11-10"
    },
    {
        id_persona: 3,
        id_empresa: 2,
        nombres_completos: "CARLOS EDUARDO RAMIREZ FLORES",
        cargo: "GERENTE DE OPERACIONES",
        correo_personal: "carlos.ramirez@outlook.com",
        celular_personal: "+51 934 567 890",
        fecha_creacion: "2022-06-10",
        fecha_actualizacion: "2024-09-15"
    },
    {
        id_persona: 4,
        id_empresa: 2,
        nombres_completos: "LUCÍA PATRICIA MENDOZA VEGA",
        cargo: "SUPERVISORA DE OBRA",
        celular_personal: "+51 945 678 901",
        fecha_creacion: "2022-08-12",
        fecha_actualizacion: "2024-10-20"
    },
    {
        id_persona: 5,
        id_empresa: 3,
        nombres_completos: "JOSÉ ANTONIO SALAZAR CRUZ",
        cargo: "GERENTE COMERCIAL",
        correo_personal: "jose.salazar@gmail.com",
        celular_personal: "+51 956 789 012",
        fecha_creacion: "2021-03-22",
        fecha_actualizacion: "2024-11-25"
    },
    {
        id_persona: 6,
        id_empresa: 3,
        nombres_completos: "ANA CAROLINA HERRERA QUISPE",
        cargo: "VENDEDORA SENIOR",
        correo_personal: "ana.herrera@yahoo.com",
        fecha_creacion: "2021-05-18",
        fecha_actualizacion: "2024-08-30"
    },
    {
        id_persona: 7,
        id_empresa: 4,
        nombres_completos: "ROBERTO MIGUEL CASTILLO ROMERO",
        cargo: "DIRECTOR EJECUTIVO",
        correo_personal: "r.castillo@gmail.com",
        celular_personal: "+51 967 890 123",
        fecha_creacion: "2020-08-05",
        fecha_actualizacion: "2024-12-01"
    },
    {
        id_persona: 8,
        id_empresa: 4,
        nombres_completos: "DIANA ISABEL VARGAS SOTO",
        cargo: "JEFA DE CALIDAD",
        correo_personal: "diana.vargas@hotmail.com",
        celular_personal: "+51 978 901 234",
        fecha_creacion: "2020-10-15",
        fecha_actualizacion: "2024-11-08"
    },
    {
        id_persona: 9,
        id_empresa: 5,
        nombres_completos: "FERNANDO ALONSO GUTIÉRREZ LÓPEZ",
        cargo: "GERENTE DE PRODUCCIÓN",
        celular_personal: "+51 989 012 345",
        fecha_creacion: "2019-05-12",
        fecha_actualizacion: "2024-09-22"
    },
    {
        id_persona: 10,
        id_empresa: 5,
        nombres_completos: "CARMEN ROSA JIMÉNEZ PEÑA",
        cargo: "DISEÑADORA TEXTIL",
        correo_personal: "carmen.jimenez@gmail.com",
        celular_personal: "+51 990 123 456",
        fecha_creacion: "2019-07-08",
        fecha_actualizacion: "2024-10-18"
    },
    {
        id_persona: 11,
        id_empresa: 6,
        nombres_completos: "LUIS ENRIQUE MORALES DÍAZ",
        cargo: "GERENTE GENERAL",
        correo_personal: "luis.morales@outlook.com",
        celular_personal: "+51 901 234 567",
        fecha_creacion: "2018-11-30",
        fecha_actualizacion: "2024-11-20"
    },
    {
        id_persona: 12,
        id_empresa: 6,
        nombres_completos: "PATRICIA ELENA RAMOS HUAMÁN",
        cargo: "INGENIERA DE MINAS",
        correo_personal: "p.ramos@yahoo.com",
        fecha_creacion: "2019-02-14",
        fecha_actualizacion: "2024-08-12"
    },
    {
        id_persona: 13,
        id_empresa: 7,
        nombres_completos: "JORGE LUIS SÁNCHEZ PAREDES",
        cargo: "JEFE DE OPERACIONES",
        correo_personal: "jorge.sanchez@gmail.com",
        celular_personal: "+51 912 345 678",
        fecha_creacion: "2021-07-18",
        fecha_actualizacion: "2024-11-15"
    },
    {
        id_persona: 14,
        id_empresa: 7,
        nombres_completos: "GABRIELA ANDREA CASTRO REYES",
        cargo: "COORDINADORA LOGÍSTICA",
        correo_personal: "gaby.castro@hotmail.com",
        celular_personal: "+51 923 456 789",
        fecha_creacion: "2021-09-22",
        fecha_actualizacion: "2024-10-28"
    },
    {
        id_persona: 15,
        id_empresa: 8,
        nombres_completos: "MIGUEL ÁNGEL FLORES BENITES",
        cargo: "DIRECTOR FARMACÉUTICO",
        correo_personal: "miguel.flores@gmail.com",
        fecha_creacion: "2020-02-14",
        fecha_actualizacion: "2024-09-05"
    },
    {
        id_persona: 16,
        id_empresa: 8,
        nombres_completos: "ROSA MARÍA CHÁVEZ ÁLVAREZ",
        cargo: "QUÍMICA FARMACÉUTICA",
        correo_personal: "rosa.chavez@outlook.com",
        celular_personal: "+51 934 567 890",
        fecha_creacion: "2020-04-20",
        fecha_actualizacion: "2024-11-12"
    },
    {
        id_persona: 17,
        id_empresa: 9,
        nombres_completos: "PEDRO JOSÉ NAVARRO CASTAÑEDA",
        cargo: "DIRECTOR ACADÉMICO",
        correo_personal: "pedro.navarro@gmail.com",
        celular_personal: "+51 945 678 901",
        fecha_creacion: "2022-01-10",
        fecha_actualizacion: "2024-11-30"
    },
    {
        id_persona: 18,
        id_empresa: 9,
        nombres_completos: "ELENA CRISTINA ROJAS MEDINA",
        cargo: "COORDINADORA DE ADMISIÓN",
        celular_personal: "+51 956 789 012",
        fecha_creacion: "2022-03-15",
        fecha_actualizacion: "2024-10-08"
    },
    {
        id_persona: 19,
        id_empresa: 10,
        nombres_completos: "RICARDO MANUEL VALDEZ ORTIZ",
        cargo: "GERENTE DE VENTAS",
        correo_personal: "ricardo.valdez@yahoo.com",
        celular_personal: "+51 967 890 123",
        fecha_creacion: "2019-09-25",
        fecha_actualizacion: "2024-12-02"
    },
    {
        id_persona: 20,
        id_empresa: 10,
        nombres_completos: "SILVIA BEATRIZ CÓRDOVA ARIAS",
        cargo: "ASESORA COMERCIAL",
        correo_personal: "silvia.cordova@gmail.com",
        fecha_creacion: "2019-11-30",
        fecha_actualizacion: "2024-09-18"
    },
    {
        id_persona: 21,
        id_empresa: 11,
        nombres_completos: "DANIEL ALBERTO ROBLES MONTENEGRO",
        cargo: "GERENTE DE PROYECTOS",
        correo_personal: "daniel.robles@outlook.com",
        celular_personal: "+51 978 901 234",
        fecha_creacion: "2021-04-08",
        fecha_actualizacion: "2024-11-18"
    },
    {
        id_persona: 22,
        id_empresa: 11,
        nombres_completos: "MÓNICA ALEJANDRA ZAMORA CUEVA",
        cargo: "ARQUITECTA DE PROYECTOS",
        correo_personal: "monica.zamora@gmail.com",
        celular_personal: "+51 989 012 345",
        fecha_creacion: "2021-06-12",
        fecha_actualizacion: "2024-10-25"
    },
    {
        id_persona: 23,
        id_empresa: 12,
        nombres_completos: "ANTONIO FRANCISCO GARCÍA PALACIOS",
        cargo: "GERENTE AGRÍCOLA",
        celular_personal: "+51 990 123 456",
        fecha_creacion: "2020-06-20",
        fecha_actualizacion: "2024-09-30"
    },
    {
        id_persona: 24,
        id_empresa: 12,
        nombres_completos: "ELIZABETH TERESA RIOS GONZALES",
        cargo: "INGENIERA AGRÓNOMA",
        correo_personal: "elizabeth.rios@hotmail.com",
        celular_personal: "+51 901 234 567",
        fecha_creacion: "2020-08-25",
        fecha_actualizacion: "2024-11-05"
    },
    {
        id_persona: 25,
        id_empresa: 13,
        nombres_completos: "HUGO MARTÍN ESPINOZA LEÓN",
        cargo: "GERENTE TÉCNICO",
        correo_personal: "hugo.espinoza@gmail.com",
        celular_personal: "+51 912 345 678",
        fecha_creacion: "2018-12-15",
        fecha_actualizacion: "2024-11-25"
    },
    {
        id_persona: 26,
        id_empresa: 13,
        nombres_completos: "CLAUDIA VANESSA MÉNDEZ TORRES",
        cargo: "INGENIERA DE REDES",
        correo_personal: "claudia.mendez@yahoo.com",
        fecha_creacion: "2019-02-20",
        fecha_actualizacion: "2024-08-15"
    },
    {
        id_persona: 27,
        id_empresa: 14,
        nombres_completos: "RAÚL FERNANDO AGUIRRE SALAS",
        cargo: "DIRECTOR DE PROYECTOS",
        correo_personal: "raul.aguirre@outlook.com",
        celular_personal: "+51 923 456 789",
        fecha_creacion: "2021-08-30",
        fecha_actualizacion: "2024-12-03"
    },
    {
        id_persona: 28,
        id_empresa: 14,
        nombres_completos: "JULIA MERCEDES PAREDES VILLA",
        cargo: "INGENIERA ELECTRÓNICA",
        correo_personal: "julia.paredes@gmail.com",
        celular_personal: "+51 934 567 890",
        fecha_creacion: "2021-10-15",
        fecha_actualizacion: "2024-11-10"
    },
    {
        id_persona: 29,
        id_empresa: 15,
        nombres_completos: "SEBASTIÁN ANDRÉS BAUTISTA CÁCERES",
        cargo: "GERENTE GENERAL",
        correo_personal: "sebastian.bautista@hotmail.com",
        fecha_creacion: "2019-03-17",
        fecha_actualizacion: "2024-09-12"
    },
    {
        id_persona: 30,
        id_empresa: 15,
        nombres_completos: "VERÓNICA LORENA CAMPOS RUIZ",
        cargo: "ADMINISTRADORA HOTELERA",
        correo_personal: "veronica.campos@gmail.com",
        celular_personal: "+51 945 678 901",
        fecha_creacion: "2019-05-22",
        fecha_actualizacion: "2024-11-12"
    },
    {
        id_persona: 31,
        id_empresa: 16,
        nombres_completos: "OSCAR GUILLERMO PEÑA SOLÍS",
        cargo: "DIRECTOR CREATIVO",
        correo_personal: "oscar.pena@yahoo.com",
        celular_personal: "+51 956 789 012",
        fecha_creacion: "2022-05-22",
        fecha_actualizacion: "2024-10-18"
    },
    {
        id_persona: 32,
        id_empresa: 16,
        nombres_completos: "NATALIA ESTEFANÍA LEÓN CORTEZ",
        cargo: "DISEÑADORA GRÁFICA",
        correo_personal: "natalia.leon@gmail.com",
        fecha_creacion: "2022-07-10",
        fecha_actualizacion: "2024-09-28"
    },
    {
        id_persona: 33,
        id_empresa: 17,
        nombres_completos: "MANUEL EDUARDO ARIAS HEREDIA",
        cargo: "GERENTE DE PRODUCCIÓN",
        correo_personal: "manuel.arias@outlook.com",
        celular_personal: "+51 967 890 123",
        fecha_creacion: "2020-10-05",
        fecha_actualizacion: "2024-11-22"
    },
    {
        id_persona: 34,
        id_empresa: 17,
        nombres_completos: "CECILIA ANGÉLICA VEGA DURAND",
        cargo: "INGENIERA INDUSTRIAL",
        correo_personal: "cecilia.vega@gmail.com",
        celular_personal: "+51 978 901 234",
        fecha_creacion: "2020-12-18",
        fecha_actualizacion: "2024-10-30"
    },
    {
        id_persona: 35,
        id_empresa: 18,
        nombres_completos: "ALBERTO JAVIER GUZMÁN PONCE",
        cargo: "GERENTE COMERCIAL",
        celular_personal: "+51 989 012 345",
        fecha_creacion: "2019-07-14",
        fecha_actualizacion: "2024-09-28"
    },
    {
        id_persona: 36,
        id_empresa: 18,
        nombres_completos: "SOFÍA CAROLINA BRAVO NÚÑEZ",
        cargo: "QUÍMICA INDUSTRIAL",
        correo_personal: "sofia.bravo@hotmail.com",
        celular_personal: "+51 990 123 456",
        fecha_creacion: "2019-09-20",
        fecha_actualizacion: "2024-11-15"
    },
    {
        id_persona: 37,
        id_empresa: 19,
        nombres_completos: "FRANCISCO MANUEL SALINAS UGARTE",
        cargo: "JEFE DE OPERACIONES",
        correo_personal: "francisco.salinas@gmail.com",
        celular_personal: "+51 901 234 567",
        fecha_creacion: "2021-02-28",
        fecha_actualizacion: "2024-12-01"
    },
    {
        id_persona: 38,
        id_empresa: 19,
        nombres_completos: "ANDREA MELISSA CAMPOS ITURBE",
        cargo: "SUPERVISORA DE SEGURIDAD",
        correo_personal: "andrea.campos@yahoo.com",
        fecha_creacion: "2021-04-15",
        fecha_actualizacion: "2024-10-12"
    },
    {
        id_persona: 39,
        id_empresa: 20,
        nombres_completos: "ENRIQUE PABLO MONTOYA CARRILLO",
        cargo: "CHEF EJECUTIVO",
        correo_personal: "enrique.montoya@outlook.com",
        celular_personal: "+51 912 345 678",
        fecha_creacion: "2020-04-12",
        fecha_actualizacion: "2024-11-08"
    },
    {
        id_persona: 40,
        id_empresa: 20,
        nombres_completos: "PAOLA KATHERINE ZÚÑIGA MIRANDA",
        cargo: "ADMINISTRADORA",
        correo_personal: "paola.zuniga@gmail.com",
        celular_personal: "+51 923 456 789",
        fecha_creacion: "2020-06-18",
        fecha_actualizacion: "2024-10-22"
    },
    {
        id_persona: 41,
        id_empresa: 21,
        nombres_completos: "RODRIGO CÉSAR VELÁSQUEZ PEÑA",
        cargo: "GERENTE DE EXPORTACIONES",
        correo_personal: "rodrigo.velasquez@gmail.com",
        fecha_creacion: "2018-09-08",
        fecha_actualizacion: "2024-10-25"
    },
    {
        id_persona: 42,
        id_empresa: 21,
        nombres_completos: "TERESA ROXANA MALDONADO CISNEROS",
        cargo: "ASISTENTE DE COMERCIO EXTERIOR",
        correo_personal: "teresa.maldonado@hotmail.com",
        celular_personal: "+51 934 567 890",
        fecha_creacion: "2018-11-12",
        fecha_actualizacion: "2024-09-18"
    },
    {
        id_persona: 43,
        id_empresa: 22,
        nombres_completos: "VÍCTOR HUGO PERALTA SÁNCHEZ",
        cargo: "DIRECTOR MÉDICO",
        correo_personal: "victor.peralta@yahoo.com",
        celular_personal: "+51 945 678 901",
        fecha_creacion: "2021-11-19",
        fecha_actualizacion: "2024-11-27"
    },
    {
        id_persona: 44,
        id_empresa: 22,
        nombres_completos: "GLORIA INES BENAVIDES ZÁRATE",
        cargo: "TECNÓLOGA MÉDICA",
        correo_personal: "gloria.benavides@gmail.com",
        fecha_creacion: "2022-01-25",
        fecha_actualizacion: "2024-10-15"
    },
    {
        id_persona: 45,
        id_empresa: 23,
        nombres_completos: "HÉCTOR FABIÁN QUIROZ REÁTEGUI",
        cargo: "GERENTE INDUSTRIAL",
        correo_personal: "hector.quiroz@outlook.com",
        celular_personal: "+51 956 789 012",
        fecha_creacion: "2020-01-25",
        fecha_actualizacion: "2024-09-15"
    },
    {
        id_persona: 46,
        id_empresa: 23,
        nombres_completos: "MARIANA LUCÍA TAPIA BUSTAMANTE",
        cargo: "INGENIERA DE PROCESOS",
        correo_personal: "mariana.tapia@gmail.com",
        celular_personal: "+51 967 890 123",
        fecha_creacion: "2020-03-30",
        fecha_actualizacion: "2024-11-20"
    },
    {
        id_persona: 47,
        id_empresa: 24,
        nombres_completos: "GUSTAVO ADOLFO CÉSPEDES PORTAL",
        cargo: "PRODUCTOR EJECUTIVO",
        correo_personal: "gustavo.cespedes@hotmail.com",
        celular_personal: "+51 978 901 234",
        fecha_creacion: "2022-03-14",
        fecha_actualizacion: "2024-11-20"
    },
    {
        id_persona: 48,
        id_empresa: 24,
        nombres_completos: "CAROLINA PATRICIA VALDIVIA PRADO",
        cargo: "COORDINADORA DE EVENTOS",
        correo_personal: "carolina.valdivia@gmail.com",
        fecha_creacion: "2022-05-20",
        fecha_actualizacion: "2024-10-08"
    },
    {
        id_persona: 49,
        id_empresa: 25,
        nombres_completos: "ARMANDO RICARDO HIDALGO SILVA",
        cargo: "GERENTE GENERAL",
        correo_personal: "armando.hidalgo@yahoo.com",
        celular_personal: "+51 989 012 345",
        fecha_creacion: "2019-06-30",
        fecha_actualizacion: "2024-10-12"
    },
    {
        id_persona: 50,
        id_empresa: 25,
        nombres_completos: "JESSICA VANESSA ARCE DOMÍNGUEZ",
        cargo: "DISEÑADORA DE INTERIORES",
        correo_personal: "jessica.arce@gmail.com",
        celular_personal: "+51 990 123 456",
        fecha_creacion: "2019-08-15",
        fecha_actualizacion: "2024-11-05"
    },
    {
        id_persona: 51,
        id_empresa: 26,
        nombres_completos: "EDUARDO ALEXIS SANTILLÁN VARGAS",
        cargo: "CONSULTOR SENIOR",
        correo_personal: "eduardo.santillan@outlook.com",
        fecha_creacion: "2021-09-05",
        fecha_actualizacion: "2024-12-04"
    },
    {
        id_persona: 52,
        id_empresa: 26,
        nombres_completos: "PAMELA CRISTINA AGUILAR LOZANO",
        cargo: "ANALISTA DE NEGOCIOS",
        correo_personal: "pamela.aguilar@gmail.com",
        celular_personal: "+51 901 234 567",
        fecha_creacion: "2021-11-18",
        fecha_actualizacion: "2024-11-12"
    },
    {
        id_persona: 53,
        id_empresa: 27,
        nombres_completos: "MARIO ALEJANDRO CORONADO ABAD",
        cargo: "JEFE DE PRODUCCIÓN",
        correo_personal: "mario.coronado@hotmail.com",
        celular_personal: "+51 912 345 678",
        fecha_creacion: "2020-07-22",
        fecha_actualizacion: "2024-11-10"
    },
    {
        id_persona: 54,
        id_empresa: 27,
        nombres_completos: "FIORELLA MARCELA IBÁÑEZ ROCHA",
        cargo: "DISEÑADORA GRÁFICA",
        correo_personal: "fiorella.ibanez@gmail.com",
        fecha_creacion: "2020-09-10",
        fecha_actualizacion: "2024-09-22"
    },
    {
        id_persona: 55,
        id_empresa: 28,
        nombres_completos: "JULIO ERNESTO CHACÓN VILLAR",
        cargo: "GERENTE DE DISTRIBUCIÓN",
        correo_personal: "julio.chacon@yahoo.com",
        celular_personal: "+51 923 456 789",
        fecha_creacion: "2018-05-18",
        fecha_actualizacion: "2024-09-30"
    },
    {
        id_persona: 56,
        id_empresa: 28,
        nombres_completos: "MIRIAM ELIZABETH OCHOA PARIONA",
        cargo: "SUPERVISORA DE ALMACÉN",
        correo_personal: "miriam.ochoa@gmail.com",
        celular_personal: "+51 934 567 890",
        fecha_creacion: "2018-07-25",
        fecha_actualizacion: "2024-11-18"
    },
    {
        id_persona: 57,
        id_empresa: 29,
        nombres_completos: "ALFREDO MARTÍN CASAS FUENTES",
        cargo: "ABOGADO SENIOR",
        correo_personal: "alfredo.casas@outlook.com",
        celular_personal: "+51 945 678 901",
        fecha_creacion: "2022-02-08",
        fecha_actualizacion: "2024-11-23"
    },
    {
        id_persona: 58,
        id_empresa: 29,
        nombres_completos: "ÁNGELA REBECA GUILLEN ACOSTA",
        cargo: "ASISTENTE LEGAL",
        correo_personal: "angela.guillen@gmail.com",
        fecha_creacion: "2022-04-15",
        fecha_actualizacion: "2024-10-05"
    },
    {
        id_persona: 59,
        id_empresa: 30,
        nombres_completos: "IGNACIO GERMÁN PORTAL MIRANDA",
        cargo: "GERENTE TÉCNICO",
        correo_personal: "ignacio.portal@hotmail.com",
        celular_personal: "+51 956 789 012",
        fecha_creacion: "2019-10-28",
        fecha_actualizacion: "2024-10-05"
    },
    {
        id_persona: 60,
        id_empresa: 30,
        nombres_completos: "YOLANDA BEATRIZ MATTOS CARRANZA",
        cargo: "INGENIERA MECÁNICA",
        correo_personal: "yolanda.mattos@gmail.com",
        celular_personal: "+51 967 890 123",
        fecha_creacion: "2019-12-15",
        fecha_actualizacion: "2024-11-28"
    }
];